export const languageCodes = [
  { language: 'english', code: 'en-US' },
  { language: 'spanish', code: 'es-ES' },
  { language: 'french', code: 'fr-FR' },
  { language: 'german', code: 'de-DE' },
  { language: 'chinese', code: 'zh-CN' },
  { language: 'japanese', code: 'ja-JP' },
  { language: 'portuguese', code: 'pt-PT' },
  { language: 'italian', code: 'it-IT' },
  { language: 'russian', code: 'ru-RU' },
  { language: 'arabic', code: 'ar-SA' },
  { language: 'korean', code: 'ko-KR' },
  { language: 'dutch', code: 'nl-NL' },
  { language: 'swedish', code: 'sv-SE' },
  { language: 'turkish', code: 'tr-TR' },
  { language: 'greek', code: 'el-GR' },
  { language: 'hebrew', code: 'he-IL' },
  { language: 'polish', code: 'pl-PL' },
  { language: 'finnish', code: 'fi-FI' },
  { language: 'indonesian', code: 'id-ID' },
  { language: 'vietnamese', code: 'vi-VN' },
  { language: 'thai', code: 'th-TH' },
  { language: 'swahili', code: 'sw-KE' },
  { language: 'danish', code: 'da-DK' },
  { language: 'norwegian', code: 'no-NO' },
  { language: 'hungarian', code: 'hu-HU' },
  { language: 'czech', code: 'cs-CZ' },
  { language: 'urdu', code: 'ur-PK' },
  { language: 'malay', code: 'ms-MY' },
] as const

export const addedLanguages = [
  'english',
  'spanish',
  'french',
  'german',
  'chinese',
  'japanese',
  'portuguese',
  'italian',
  'russian',
  'arabic',
  'korean',
  'dutch',
  'swedish',
  'turkish',
  'greek',
  'hebrew',
  'polish',
  'finnish',
  'indonesian',
  'vietnamese',
  'thai',
  'swahili',
  'danish',
  'norwegian',
  'hungarian',
  'czech',
  'korean',
  'urdu',
  'malay',
] as const

export const pos = [
  'noun',
  'verb',
  'adjective',
  'adverb',
  'pronoun',
  'preposition',
  'postposition',
  'conjunction',
  'interjection',
  'numeral',
  'determiner',
] as const

export const levels = ['a1', 'a2', 'b1', 'b2', 'c1', 'c2'] as const
